$DecomServers = @(
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''
    ''    
)
$DecomServers | ForEach-Object{
    $group = $_+'\'
    $readonly = $_+'\'
    $scans = $_+'\'
    $apps = $_+'\'
    get-smbmapping | Where-Object RemotePath -eq $group | remove-smbmapping -Force
    get-smbmapping | Where-Object RemotePath -eq $readonly | remove-smbmapping -Force
    get-smbmapping | Where-Object RemotePath -eq $scans | remove-smbmapping -Force
    get-smbmapping | Where-Object RemotePath -eq $apps | remove-smbmapping -Force
}